name: gerador_de_cv
description: A Flutter app to generate a visually appealing resume

# The following line specifies the version of the Flutter framework that your
# app depends on.
dependencies:
  flutter:
    sdk: flutter

# The following line specifies the version of the package that your app depends on.
# In this case, we're using the latest version of the `pdf` package, which allows
# us to generate PDF files from our app.
dependencies:
  pdf: ^1.7.4

# The following lines specify the minimum and maximum versions of the Flutter
# framework that your app supports.
flutter:
  min_sdk_version: 21
  max_sdk_version: 38

# The following line specifies the platforms that your app supports.
# In this case, we're targeting Android and iOS.
platforms:
  android:
    target: android-R
  ios:
    deployment_target: '12.0'

# The following line specifies the build modes that your app supports.
# In this case, we're supporting both debug and release builds.
build_modes:
  debug:
    defines:
      - FLUTTER_DEBUG=true
  release:
    defines:
      - FLUTTER_DEBUG=false

# The following lines specify the assets that your app uses.
# In this case, we're including a logo image and a font.
assets:
  - assets/logo.png
  - assets/fonts/Roboto-Regular.ttf

# The following line specifies the fonts that your app uses.
# In this case, we're using the Roboto font.
fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
